### ISSUE TITLE
DPS JSON attributes are only True or False and not the actual values.

### ISSUE THREAD

**Issue by ANeed2Py** [TradeFace/tuyagateway#107]
Hi,

I have a few Tuya Switch plugs with built in Energy monitoring.
I use these switches in Home Assistant and have set them up with Tuyagateway and Gismocaster via MQTT and controlling them is fine once I had worked out how Gismocaster worked.
The issue is I can't get the Energy reading from the switches.

I have tried all sorts of configurations in Gismocaster and I don't get any values.

All I see in my Mosquitto server is:
tuya/54170761d8f15b127833/attributes {"1": true, "2": false,  "4": false, "5": false, "6": false}

dps 1 = Switch is on or off (true or false and this works / changes depending on the state)
dps 2 = ? (I have no idea what this is and it never changes)
dps 4, 5 and 6 should be Current, Power, Voltage values adn they are always "false".

However if I look in the logs for Tuyagateway, I can see that Tuyaface is receiving the correct dps values.
2021-01-18 17:27:40,119 DEBUG    (Thread-23) [tuyaface] (xx.xx.xx.xx) received msg (seq 0): [8:STATUS] rc: [0] payload: [{"devId":"54170761d8f15b127833","dps":{"4":161,"5":269,"6":2448},"t":1610990859}]

Should I be getting values and not just True and False for dps 4, 5 & 6?
Is Gismocaster correctly configured. I can't find a way to get the values and I've tried lots of different setups.
Is there a way to get the value direct from Tuyaface and send that information via MQTT? (I assume that's what Tuyagateway is there to do though)

Many thanks,

**Comment by TradeFace** [comment]
Hey, do you have the latest version of TG? I remember I did some changes regarding the issue you're describing. A few days ago I merged all development changes to master. Not, quite sure... but I think that could solve the problem.

**Comment by TradeFace** [comment]
Hmmm, that was already an older change. You might have mapped the values to boolean in gismocaster.

**Comment by ANeed2Py** [comment]
Hi,
I have checked that I'm using the latest version of TuyaGateway 2.0.3.
I reinstalled everything also but still see the same issues.
Tuyaface detects the dps 4,5 & 6 as values but across MQTT I only get True or False as I mentioned before.

It took me a long time to work out how to get a switch to work in GismoCaster and I may well have it not setup correctly for the Energy measurement dps's but every way I try, I can't seem to get it to work.
It seems to create extra switches with the other dps's (4.5. & 6) when I add them to the Gismo I created for the switch itself.
I assume you need to add these dps's to the same Gismo as the switch?
I did try and make them separate sensors but it didn't allow me to put in the switch id number etc twice in GismoCaster, which I think is what it will do anyway.

Is there any video's or tutorials available for setting up a switch and adding dps's to it?
I see from the issues list that there are others with similar issues in controlling multi switches from different dps's and wonder if this is something similar? 

Many thanks for your help.

**Comment by TradeFace** [comment]
Nope no tutors or videos... 
What you are "actually" doing in gismocaster is creating a config for HA and telling TuyaGateway how to handle it. The config for HA is bound to the rules described here https://www.home-assistant.io/docs/mqtt/discovery/ 

So when you configure something as a switch you have the options as described here https://www.home-assistant.io/integrations/switch.mqtt/

Mapping a power value to a state topic would be kinda strange.... HA doesn't understand that. And expects a boolean value. So GismoCaster tells TuyaGateway in that case to interpret the value as boolean. All values the device returns to TuyaGateway are passed along via the  json_attributes_topic. So you can pull you values from there for further processing in your automation.
hth

**Comment by ANeed2Py** [comment]
I think it must be an issue with how i have the Gismo setuo in GismoCaster.
So I have a switch setup as a Gismo which seems to work great.
Where do i setup the other dps's?
Do i add them to the Gismo model I created for the switch or do i create a new Gismo Model?

**Comment by TradeFace** [comment]
listen in HA to the  json_attributes_topic. e.g. tuya/<device-id>/attributes in the backend listener. These dp values don't have to be mapped to a topic. It is returned by default

**Comment by ANeed2Py** [comment]
Many thanks for being patient with me.
We I listen to the tuya//attributes I get the following:

Message 10 received on tuya/54170761d8f15b127833/attributes at 15:57:

{
    "1": true,
    "2": false,
    "4": false,
    "5": false,
    "6": true
}

I also looked at the MQTT messages with MQTT.fx:

![image](https://user-images.githubusercontent.com/55873909/105639167-95f1d700-5e6e-11eb-99ec-9044bce98efb.png)

**Comment by TradeFace** [comment]
did you remove the dp mappings for 4,5 and 6 in gismocaster?

**Comment by ANeed2Py** [comment]
I did and then I just added dps 4.

![image](https://user-images.githubusercontent.com/55873909/105641565-88434e00-5e7c-11eb-9aa9-e7d674749251.png)

![image](https://user-images.githubusercontent.com/55873909/105641569-942f1000-5e7c-11eb-9e65-4de8e98c607a.png)

There is no dps 4 present in the Gismo Model or Gismo either.

**Comment by TradeFace** [comment]
There seems to be a problem in the code.

**Comment by Schnittcher** [comment]
hi, will you fix this problem?
